admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

model:
    resource: "@ModelBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

