admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

#model:
#    resource: "@ModelBundle/Controller/"
#    type:     annotation
#    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@ModelBundle/Resources/config/routing.yml"
    prefix:   /