<?php

namespace Blog\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RegistrationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Blog\AdminBundle\Controller\RegistrationController();
        return $instance;
    }
}
